# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_btn_sunucu_tara(object):
    def setupUi(self, btn_sunucu_tara):
        btn_sunucu_tara.setObjectName("btn_sunucu_tara")
        btn_sunucu_tara.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(btn_sunucu_tara)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 200, 91, 21))
        self.pushButton.setObjectName("pushButton")
        self.cb_sunucu = QtWidgets.QComboBox(self.centralwidget)
        self.cb_sunucu.setGeometry(QtCore.QRect(250, 220, 81, 31))
        self.cb_sunucu.setObjectName("cb_sunucu")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 180, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 170, 61, 21))
        self.label_2.setObjectName("label_2")
        self.btn_etiket_tara = QtWidgets.QPushButton(self.centralwidget)
        self.btn_etiket_tara.setGeometry(QtCore.QRect(430, 190, 81, 21))
        self.btn_etiket_tara.setObjectName("btn_etiket_tara")
        self.list_etiket = QtWidgets.QListWidget(self.centralwidget)
        self.list_etiket.setGeometry(QtCore.QRect(400, 210, 161, 91))
        self.list_etiket.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.list_etiket.setObjectName("list_etiket")
        self.txt_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_ip.setGeometry(QtCore.QRect(630, 200, 113, 20))
        self.txt_ip.setObjectName("txt_ip")
        self.btn_baslat = QtWidgets.QPushButton(self.centralwidget)
        self.btn_baslat.setGeometry(QtCore.QRect(640, 230, 75, 23))
        self.btn_baslat.setObjectName("btn_baslat")
        self.btn_durdur = QtWidgets.QPushButton(self.centralwidget)
        self.btn_durdur.setGeometry(QtCore.QRect(640, 260, 75, 23))
        self.btn_durdur.setObjectName("btn_durdur")
        self.txt_konsol = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_konsol.setGeometry(QtCore.QRect(30, 340, 261, 201))
        self.txt_konsol.setObjectName("txt_konsol")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 180, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 320, 51, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_5.setObjectName("label_5")
        self.btn_kurulum_ac = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kurulum_ac.setGeometry(QtCore.QRect(20, 40, 131, 31))
        self.btn_kurulum_ac.setObjectName("btn_kurulum_ac")
        btn_sunucu_tara.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(btn_sunucu_tara)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuOPC_DA_OPC_UA_GATEWAY = QtWidgets.QMenu(self.menubar)
        self.menuOPC_DA_OPC_UA_GATEWAY.setObjectName("menuOPC_DA_OPC_UA_GATEWAY")
        btn_sunucu_tara.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(btn_sunucu_tara)
        self.statusbar.setObjectName("statusbar")
        btn_sunucu_tara.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuOPC_DA_OPC_UA_GATEWAY.menuAction())

        self.retranslateUi(btn_sunucu_tara)
        QtCore.QMetaObject.connectSlotsByName(btn_sunucu_tara)

    def retranslateUi(self, btn_sunucu_tara):
        _translate = QtCore.QCoreApplication.translate
        btn_sunucu_tara.setWindowTitle(_translate("btn_sunucu_tara", "MainWindow"))
        self.pushButton.setText(_translate("btn_sunucu_tara", "Sunucuları Tara"))
        self.label.setText(_translate("btn_sunucu_tara", "ProgID"))
        self.label_2.setText(_translate("btn_sunucu_tara", "Etiket Seçimi"))
        self.btn_etiket_tara.setText(_translate("btn_sunucu_tara", "Etiketleri Tara"))
        self.txt_ip.setText(_translate("btn_sunucu_tara", "0.0.0.0"))
        self.btn_baslat.setText(_translate("btn_sunucu_tara", "Başlat"))
        self.btn_durdur.setText(_translate("btn_sunucu_tara", "Durdur"))
        self.label_3.setText(_translate("btn_sunucu_tara", "Başlatma Ve IP"))
        self.label_4.setText(_translate("btn_sunucu_tara", "Canlı Veri"))
        self.label_5.setText(_translate("btn_sunucu_tara", "Kurulum"))
        self.btn_kurulum_ac.setText(_translate("btn_sunucu_tara", "⚙️ Sistem Kurulumları"))
        self.menuOPC_DA_OPC_UA_GATEWAY.setTitle(_translate("btn_sunucu_tara", "OPC DA - OPC UA GATEWAY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    btn_sunucu_tara = QtWidgets.QMainWindow()
    ui = Ui_btn_sunucu_tara()
    ui.setupUi(btn_sunucu_tara)
    btn_sunucu_tara.show()
    sys.exit(app.exec_())
